<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IncidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('incidents')->insert([
            [
                "title" => "Bug página web",
                "text" => "No crea un usuario en el registro",
                "user_id" => "1",
                "departament_id" => "1",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "2",
                "minutes" => "30",
                'created_at' => now(),
            ],
            [
                "title" => "Problema con la función de búsqueda",
                "text" => "La función de búsqueda no encuentra resultados",
                "user_id" => "2",
                "departament_id" => "3",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "3",
                "minutes" => "60",
                'created_at' => now(),
            ],
            [
                "title" => "Error en la página de inicio",
                "text" => "La página de inicio no carga correctamente",
                "user_id" => "1",
                "departament_id" => "2",
                "status_id" => "2",
                "priority_id" => "3",
                "category_id" => "2",
                "minutes" => "45",
                'created_at' => now(),
            ],
            [
                "title" => "Error en la página de contacto",
                "text" => "El formulario de contacto no envía correos electrónicos",
                "user_id" => "2",
                "departament_id" => "1",
                "status_id" => "1",
                "priority_id" => "1",
                "category_id" => "8",
                "minutes" => "20",
                'created_at' => now(),
            ],
            [
                "title" => "Problema con la carrito de compras",
                "text" => "El carrito de compras no guarda los productos seleccionados",
                "user_id" => "2",
                "departament_id" => "4",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "3",
                "minutes" => "40",
                "created_at" => now(),
            ],
            [
                "title" => "Error en la funcionalidad de chat en vivo",
                "text" => "Los mensajes del chat en vivo no se envían correctamente",
                "user_id" => "2",
                "departament_id" => "2",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "3",
                "minutes" => "55",
                "created_at" => now(),
            ],
            [
                "title" => "Problema de seguridad en la aplicación móvil",
                "text" => "La aplicación móvil muestra datos sensibles sin autenticación",
                "user_id" => "1",
                "departament_id" => "3",
                "status_id" => "2",
                "priority_id" => "3",
                "category_id" => "2",
                "minutes" => "70",
                "created_at" => now(),
            ],
            [
                "title" => "Error en la generación de informes",
                "text" => "La generación de informes falla con grandes conjuntos de datos",
                "user_id" => "2",
                "departament_id" => "4",
                "status_id" => "1",
                "priority_id" => "1",
                "category_id" => "3",
                "minutes" => "25",
                "created_at" => now(),
            ],
            [
                "title" => "Problema con la conexión a Internet",
                "text" => "La conexión a Internet es intermitente en la oficina",
                "user_id" => "1",
                "departament_id" => "1",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "4",
                "minutes" => "50",
                "created_at" => now(),
            ],
            [
                "title" => "Error en el sistema de facturación",
                "text" => "Los clientes informan discrepancias en las facturas",
                "user_id" => "2",
                "departament_id" => "3",
                "status_id" => "1",
                "priority_id" => "1",
                "category_id" => "5",
                "minutes" => "35",
                "created_at" => now(),
            ],
            [
                "title" => "Problema con el correo electrónico",
                "text" => "No se pueden enviar correos electrónicos desde las cuentas de la empresa",
                "user_id" => "1",
                "departament_id" => "2",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "6",
                "minutes" => "40",
                "created_at" => now(),
            ],
            [
                "title" => "Error en la aplicación de gestión de proyectos",
                "text" => "La aplicación se cierra inesperadamente al cargar grandes proyectos",
                "user_id" => "2",
                "departament_id" => "1",
                "status_id" => "2",
                "priority_id" => "3",
                "category_id" => "7",
                "minutes" => "55",
                "created_at" => now(),
            ],
            [
                "title" => "Problema con la impresora de la oficina",
                "text" => "La impresora no imprime documentos correctamente",
                "user_id" => "1",
                "departament_id" => "1",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "4",
                "minutes" => "30",
                "created_at" => now(),
            ],
            [
                "title" => "Error en la aplicación contable",
                "text" => "La aplicación contable muestra cifras incorrectas en los informes",
                "user_id" => "2",
                "departament_id" => "3",
                "status_id" => "1",
                "priority_id" => "1",
                "category_id" => "5",
                "minutes" => "60",
                "created_at" => now(),
            ],
            [
                "title" => "Problema con la red Wi-Fi en la sala de reuniones",
                "text" => "La conexión Wi-Fi es débil en la sala de reuniones",
                "user_id" => "1",
                "departament_id" => "2",
                "status_id" => "2",
                "priority_id" => "3",
                "category_id" => "4",
                "minutes" => "45",
                "created_at" => now(),
            ],
            [
                "title" => "Error en la aplicación de recursos humanos",
                "text" => "La aplicación de recursos humanos no registra las nuevas contrataciones",
                "user_id" => "2",
                "departament_id" => "4",
                "status_id" => "1",
                "priority_id" => "1",
                "category_id" => "6",
                "minutes" => "20",
                "created_at" => now(),
            ],
            [
                "title" => "Problema con la página de inicio de sesión",
                "text" => "Los usuarios no pueden iniciar sesión en la plataforma",
                "user_id" => "2",
                "departament_id" => "2",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "3",
                "minutes" => "40",
                "created_at" => now(),
            ],
            [
                "title" => "Error en la aplicación de gestión de tareas",
                "text" => "Las tareas asignadas desaparecen de la aplicación",
                "user_id" => "2",
                "departament_id" => "1",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "7",
                "minutes" => "55",
                "created_at" => now(),
            ],
            [
                "title" => "Problema con la videoconferencia",
                "text" => "La calidad del video en las conferencias es baja",
                "user_id" => "1",
                "departament_id" => "3",
                "status_id" => "2",
                "priority_id" => "3",
                "category_id" => "2",
                "minutes" => "70",
                "created_at" => now(),
            ],
            [
                "title" => "Error en la aplicación de análisis de datos",
                "text" => "La aplicación de análisis de datos no carga los conjuntos grandes",
                "user_id" => "2",
                "departament_id" => "4",
                "status_id" => "1",
                "priority_id" => "1",
                "category_id" => "3",
                "minutes" => "25",
                "created_at" => now(),
            ],
            [
                "title" => "Problema con la configuración del correo electrónico",
                "text" => "Los correos electrónicos no se sincronizan correctamente en los dispositivos",
                "user_id" => "1",
                "departament_id" => "1",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "6",
                "minutes" => "50",
                "created_at" => now(),
            ],
            [
                "title" => "Error en la aplicación de gestión de inventario",
                "text" => "La aplicación de inventario no actualiza las existencias en tiempo real",
                "user_id" => "2",
                "departament_id" => "3",
                "status_id" => "1",
                "priority_id" => "2",
                "category_id" => "5",
                "minutes" => "40",
                "created_at" => now(),
            ],
        ]);        
    }
}
